# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'projectOne' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'SwiftMessages'
 pod 'RealmSwift'
 pod 'Alamofire', '~> 4.3'
 pod 'SwiftyJSON'
 pod 'MBProgressHUD', '~> 1.0.0'
pod 'Google/Analytics'
pod 'OneSignal', '~> 2.0'
pod 'Google-Mobile-Ads-SDK'
pod 'Kingfisher'
pod 'Firebase/Core'
pod 'iOS-blur'
end
